### ISSUE TITLE
Further concurrency related corruption in @pending

### ISSUE THREAD

**Issue by ripienaar** [nats-io/ruby-nats#118]
So unfortunately this is not quite fixed yet, and this time I do not know enough about EM to fix it.

Am doing some tests sending large messages as quick as I possibly can, my broker is a bit far away network wise so the pending queue can grow a bit between drains, and draining can take a bit (milliseconds, but still significant).

So `flush_pending` can take a while to finish and at the same time `send_command` can be adding stuff to it while `flush_pending` is happening. `flush_pending` will still nil the Array which messes it all up.  Given that a user of the gem want to publish at any time stuff is happening concurrently and this Array ends up nil at times.

Best option is to never nil the array so appending to it always works.  To do this a bunch has to be rewritten, if this was not EM I would use the `Queue` class that's thread safe and have a mode to have a blocking listener on it. One thread would sit and blocking listen on the Queue and publish soon as there's a message and any other thread would just append to the Queue - it's built in thread safety makes that fine.  There has to be some EM equivelant of that, restructuring this code so that that `@pending` is always appendable is the only sane thing I think.

```
@q = Queue.new

Thread.new { loop { publish_to_network(@q.pop) } }

# other threads can at any time safely << to @q and message is dispatched soon as its written
```

I have no idea what the equivelant is in EM world, but this to me seems like the right structure rather than a plain Array and especially key that we never nil the Array holding var.

```
NoMethodError: undefined method `<<' for nil:NilClass
        from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/nats-0.7.1/lib/nats/client.rb:874:in `send_command'
        from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/nats-0.7.1/lib/nats/client.rb:375:in `publish'
        from /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/nats-0.7.1/lib/nats/client.rb:253:in `publish'
```

**Comment by wallyqs** [comment]
Thanks for the report.  Think this could happen when calling `publish` or any method which buffers a command from another thread from the one Eventmachine is using. We might get more mileage with this style of usage by moving all the `@pending` handling into an Eventmachine `next_tick` block to take advantage of the mutex there so that calls which append to the buffer become serialized, though can't do this by default since affects performance from clients which are single threaded using EM and don't have this issue.

Could possibly add something like a "use `next_tick` for buffering pending" option to `connect` for this, have a branch up where trying to address this use case here https://github.com/nats-io/ruby-nats/compare/master...wallyqs:next-tick-flusher (does not get error on append when EM is running on a different thread from the one where publish call is happening)

**Comment by ripienaar** [comment]
Yeah that'll work, I am seriously considering writing a non EM based on myself, it's like a different programming language and not at all compatible with general ruby programs :(

**Comment by wallyqs** [comment]
Alternative client without EM dependencies which is thread safe is available now at https://github.com/nats-io/pure-ruby-nats so recommending that one for this type of usage for now.
