### ISSUE TITLE
allow discovery of servers to be disabled

### ISSUE THREAD

**Issue by ripienaar** [nats-io/ruby-nats#127]
The new feature to discover servers to connect to is great but not universally desirable.

NATS daemons that goes via NAT or some other form of intermediate hop/proxy network device will announce their private address and not the public 'service' address.

These may well be unroutable to clients and without any way of mapping those to routeable addresses this feature will introduce uneeded delays in reconnects while clients attempt to connect to things they never can.

So on by default but disablable would be great.

For example nodes behind EC2 or Scaleways clouds are assigned private IPs and you might want to have other infrastructure connect to these nodes, there's a cloud provider level NAT, but other nodes lets say on Google Cloud would never be able to connect to the announced server list.

**Comment by kozlovic** [comment]
Good point, but do you think that it should be a global setting in the server instead of on each client? If you agree, then I would create an issue in gnatsd repo and link to this one.

**Comment by ripienaar** [comment]
I wondered myself and did not know which would be best, I suspect server side would be handy, but on the other hand I can imagine a case where someone has clients many in EC2 and few in Google Cloud, they might want to disable the GC ones from this behaviour only, perhaps pointing GC ones at a ELB or something?

It's difficult to say, so I opened it here looking for input

**Comment by ripienaar** [comment]
Or mobile clients all at the ELB and servers on the lan via discovery etc, there server side only would not be great

**Comment by kozlovic** [comment]
@ripienaar After much discussion with the rest of the engineering team, we have decided to implement a server global switch instead of allowing this at the client library level. It will still be possible to have a mesh of servers with different settings and only clients connected to servers with the switch off will not receive async INFOs while other will be able to.
I have created an issue in gnatsd repo and referenced this issue for tracking purposes.

Thanks again for your feedback and I will now close this issue. Feel free to re-open.

**Comment by ripienaar** [comment]
That sounds reasonable, thanks @kozlovic

**Comment by kozlovic** [comment]
@ripienaar Just to let you know that his has been addressed and merged in master: https://github.com/nats-io/gnatsd/issues/322
