### ISSUE TITLE
Feature Request: Non-EM client

### ISSUE THREAD

**Issue by aemadrid** [nats-io/ruby-nats#72]
Have you considered creating a a client that does not depend on EventMachine?

**Comment by atombender** [comment]
Another vote for this. I'm not very familiar with EventMachine (and I don't want to be!) — but it seems very invasive when you have an existing app infrastructure which is completely synchronous, which most of the Ruby world is, including our own codebases.

So far, I've figured out that you can run EM in a separate thread, and that you can call NATS methods via `EM.next_tick`. But this poses a problem for synchronous code that wants, for example, to do RPC calls. As far as I can see, you have to resort to IPC. This is the best I've come up with so far:

```ruby
def rpc(message, &block)
  v = Concurrent::MVar.new  # from concurrent-ruby
  EM.next_tick do
    NATS.request(message) do |response|
      v.put(response)
    end
  end
  return v.take
end
```

Of course, this is too simplistic to capture NATS connection errors, since they happen in the EM loop — all you can do it deal with timeouts.

**Comment by tarcieri** [comment]
If you're looking for a portable Java NIO-like multiplexing library which works "equally" (for the most part) well on CRuby and JRuby, check out nio4r:

https://github.com/celluloid/nio4r

It provides a fairly low-level API but wraps up the mechanics of using syscalls like epoll and kqueue portably, and has a native Java backend to utilize Java NIO.

**Comment by ripienaar** [comment]
+1 for no EventMachine.  I'd be happy if that non EM client would only be synchronous too - which should make things a lot easier

**Comment by nickcarenza** [comment]
Having trouble using this library in a logstash output plugin that uses JRuby. Anyone have any luck with this lib in JRuby?

**Comment by nickcarenza** [comment]
Apparently there is a java-specific eventmachine.

https://github.com/eventmachine/eventmachine/issues/724

**Comment by ripienaar** [comment]
There is a pure-ruby eventmachine http://eventmachine.rubyforge.org/docs/PURE_RUBY.html which in basic tests works for me - if I activate it in a working app it keeps working

Would you consider adding this to the test matrix so we can see how it goes? You can activate it by just setting `EVENTMACHINE_LIBRARY="pure_ruby"` environment

**Comment by wallyqs** [comment]
@ripienaar Good idea, I will give it a try and add it to the test matrix, thanks for sharing.

**Comment by tarcieri** [comment]
For what it's worth, my latest Ruby socket library is nearing a useful state:

https://github.com/socketry/socketry

It implements asynchronous I/O using Ruby standard library functionality alone, providing thread-safe timeouts. It's tested on modern versions of MRI (2.2+) and JRuby (9.1+)

**Comment by wallyqs** [comment]
Hi @tarcieri have an in the works [pure ruby based implementation](https://github.com/wallyqs/pure-ruby-nats) of the nats client which aims to be thread safe and looks like this might be useful, thanks for sharing! :)

**Comment by wallyqs** [comment]
Hi all, I have released a version of the client which does not depend on Eventmachine, available on rubygems as `gem install nats-pure`.
https://github.com/nats-io/pure-ruby-nats

Any feedback is very appreciated, thanks!

**Comment by ripienaar** [comment]
@wallyqs awesome, I'll be giving this a play soon, thanks!
